package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/characters/CharacterMockup.png", "assets/images/characters/CharacterMockup.png");
			type.set ("assets/images/characters/CharacterMockup.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/characters/donkeycarry.png", "assets/images/characters/donkeycarry.png");
			type.set ("assets/images/characters/donkeycarry.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/resources/0.png", "assets/images/resources/0.png");
			type.set ("assets/images/resources/0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/resources/1.png", "assets/images/resources/1.png");
			type.set ("assets/images/resources/1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/resources/2.png", "assets/images/resources/2.png");
			type.set ("assets/images/resources/2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/resources/3.png", "assets/images/resources/3.png");
			type.set ("assets/images/resources/3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/resources/4.png", "assets/images/resources/4.png");
			type.set ("assets/images/resources/4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/resources/5.png", "assets/images/resources/5.png");
			type.set ("assets/images/resources/5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Dessertland tile 128x128.png", "assets/images/tiles/Dessertland tile 128x128.png");
			type.set ("assets/images/tiles/Dessertland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Grassland tile 128x128.png", "assets/images/tiles/Grassland tile 128x128.png");
			type.set ("assets/images/tiles/Grassland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Rockland tile 128x128.png", "assets/images/tiles/Rockland tile 128x128.png");
			type.set ("assets/images/tiles/Rockland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Sea tile 128x128.png", "assets/images/tiles/Sea tile 128x128.png");
			type.set ("assets/images/tiles/Sea tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Town NE tile 128x128.png", "assets/images/tiles/Town NE tile 128x128.png");
			type.set ("assets/images/tiles/Town NE tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Town NW tile 128x128.png", "assets/images/tiles/Town NW tile 128x128.png");
			type.set ("assets/images/tiles/Town NW tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Town SE tile 128x128.png", "assets/images/tiles/Town SE tile 128x128.png");
			type.set ("assets/images/tiles/Town SE tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Town SW tile 128x128.png", "assets/images/tiles/Town SW tile 128x128.png");
			type.set ("assets/images/tiles/Town SW tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/TownGrassland tile 128x128.png", "assets/images/tiles/TownGrassland tile 128x128.png");
			type.set ("assets/images/tiles/TownGrassland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/Undiscovered tile 128x128.png", "assets/images/tiles/Undiscovered tile 128x128.png");
			type.set ("assets/images/tiles/Undiscovered tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles/WaterCalm tile 128x128.png", "assets/images/tiles/WaterCalm tile 128x128.png");
			type.set ("assets/images/tiles/WaterCalm tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/APLeftButton.png", "assets/images/UI/APLeftButton.png");
			type.set ("assets/images/UI/APLeftButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/backButton.png", "assets/images/UI/backButton.png");
			type.set ("assets/images/UI/backButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/background.png", "assets/images/UI/background.png");
			type.set ("assets/images/UI/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/baseButton.png", "assets/images/UI/baseButton.png");
			type.set ("assets/images/UI/baseButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/buildUpgradesButton.png", "assets/images/UI/buildUpgradesButton.png");
			type.set ("assets/images/UI/buildUpgradesButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/createTownButton.png", "assets/images/UI/createTownButton.png");
			type.set ("assets/images/UI/createTownButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/englishButton.png", "assets/images/UI/englishButton.png");
			type.set ("assets/images/UI/englishButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/exitButton.png", "assets/images/UI/exitButton.png");
			type.set ("assets/images/UI/exitButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/exitMainButton.png", "assets/images/UI/exitMainButton.png");
			type.set ("assets/images/UI/exitMainButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/inventory3x3.png", "assets/images/UI/inventory3x3.png");
			type.set ("assets/images/UI/inventory3x3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/inventoryButton.png", "assets/images/UI/inventoryButton.png");
			type.set ("assets/images/UI/inventoryButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/inventorySpot.png", "assets/images/UI/inventorySpot.png");
			type.set ("assets/images/UI/inventorySpot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/joinTownButton.png", "assets/images/UI/joinTownButton.png");
			type.set ("assets/images/UI/joinTownButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/languageButton.png", "assets/images/UI/languageButton.png");
			type.set ("assets/images/UI/languageButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/menuButton.png", "assets/images/UI/menuButton.png");
			type.set ("assets/images/UI/menuButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/musicSlider.png", "assets/images/UI/musicSlider.png");
			type.set ("assets/images/UI/musicSlider.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/navigateButton.png", "assets/images/UI/navigateButton.png");
			type.set ("assets/images/UI/navigateButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/nederlandsButton.png", "assets/images/UI/nederlandsButton.png");
			type.set ("assets/images/UI/nederlandsButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/optionsButton.png", "assets/images/UI/optionsButton.png");
			type.set ("assets/images/UI/optionsButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/returnToTownButton.png", "assets/images/UI/returnToTownButton.png");
			type.set ("assets/images/UI/returnToTownButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/selectedSpot.png", "assets/images/UI/selectedSpot.png");
			type.set ("assets/images/UI/selectedSpot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/SFXSlider.png", "assets/images/UI/SFXSlider.png");
			type.set ("assets/images/UI/SFXSlider.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/startButton.png", "assets/images/UI/startButton.png");
			type.set ("assets/images/UI/startButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/test.png", "assets/images/UI/test.png");
			type.set ("assets/images/UI/test.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/title.png", "assets/images/UI/title.png");
			type.set ("assets/images/UI/title.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/tutorialButton.png", "assets/images/UI/tutorialButton.png");
			type.set ("assets/images/UI/tutorialButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/visitBankButton.png", "assets/images/UI/visitBankButton.png");
			type.set ("assets/images/UI/visitBankButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/volumeButton.png", "assets/images/UI/volumeButton.png");
			type.set ("assets/images/UI/volumeButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/watch.png", "assets/images/UI/watch.png");
			type.set ("assets/images/UI/watch.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/UI/zoneActionsButton.png", "assets/images/UI/zoneActionsButton.png");
			type.set ("assets/images/UI/zoneActionsButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/sounds/beep.ogg", "flixel/sounds/beep.ogg");
			type.set ("flixel/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/sounds/flixel.ogg", "flixel/sounds/flixel.ogg");
			type.set ("flixel/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/fonts/nokiafc22.ttf", "flixel/fonts/nokiafc22.ttf");
			type.set ("flixel/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/fonts/monsterrat.ttf", "flixel/fonts/monsterrat.ttf");
			type.set ("flixel/fonts/monsterrat.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/images/ui/button.png", "flixel/images/ui/button.png");
			type.set ("flixel/images/ui/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/characters/CharacterMockup.png", "images/characters/CharacterMockup.png");
			type.set ("images/characters/CharacterMockup.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/characters/donkeycarry.png", "images/characters/donkeycarry.png");
			type.set ("images/characters/donkeycarry.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/images-go-here.txt", "images/images-go-here.txt");
			type.set ("images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("images/resources/0.png", "images/resources/0.png");
			type.set ("images/resources/0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/resources/1.png", "images/resources/1.png");
			type.set ("images/resources/1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/resources/2.png", "images/resources/2.png");
			type.set ("images/resources/2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/resources/3.png", "images/resources/3.png");
			type.set ("images/resources/3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/resources/4.png", "images/resources/4.png");
			type.set ("images/resources/4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/resources/5.png", "images/resources/5.png");
			type.set ("images/resources/5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Dessertland tile 128x128.png", "images/tiles/Dessertland tile 128x128.png");
			type.set ("images/tiles/Dessertland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Grassland tile 128x128.png", "images/tiles/Grassland tile 128x128.png");
			type.set ("images/tiles/Grassland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Rockland tile 128x128.png", "images/tiles/Rockland tile 128x128.png");
			type.set ("images/tiles/Rockland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Sea tile 128x128.png", "images/tiles/Sea tile 128x128.png");
			type.set ("images/tiles/Sea tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Town NE tile 128x128.png", "images/tiles/Town NE tile 128x128.png");
			type.set ("images/tiles/Town NE tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Town NW tile 128x128.png", "images/tiles/Town NW tile 128x128.png");
			type.set ("images/tiles/Town NW tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Town SE tile 128x128.png", "images/tiles/Town SE tile 128x128.png");
			type.set ("images/tiles/Town SE tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Town SW tile 128x128.png", "images/tiles/Town SW tile 128x128.png");
			type.set ("images/tiles/Town SW tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/TownGrassland tile 128x128.png", "images/tiles/TownGrassland tile 128x128.png");
			type.set ("images/tiles/TownGrassland tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/Undiscovered tile 128x128.png", "images/tiles/Undiscovered tile 128x128.png");
			type.set ("images/tiles/Undiscovered tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/tiles/WaterCalm tile 128x128.png", "images/tiles/WaterCalm tile 128x128.png");
			type.set ("images/tiles/WaterCalm tile 128x128.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/APLeftButton.png", "images/UI/APLeftButton.png");
			type.set ("images/UI/APLeftButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/backButton.png", "images/UI/backButton.png");
			type.set ("images/UI/backButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/background.png", "images/UI/background.png");
			type.set ("images/UI/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/baseButton.png", "images/UI/baseButton.png");
			type.set ("images/UI/baseButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/buildUpgradesButton.png", "images/UI/buildUpgradesButton.png");
			type.set ("images/UI/buildUpgradesButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/createTownButton.png", "images/UI/createTownButton.png");
			type.set ("images/UI/createTownButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/englishButton.png", "images/UI/englishButton.png");
			type.set ("images/UI/englishButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/exitButton.png", "images/UI/exitButton.png");
			type.set ("images/UI/exitButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/exitMainButton.png", "images/UI/exitMainButton.png");
			type.set ("images/UI/exitMainButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/inventory3x3.png", "images/UI/inventory3x3.png");
			type.set ("images/UI/inventory3x3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/inventoryButton.png", "images/UI/inventoryButton.png");
			type.set ("images/UI/inventoryButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/inventorySpot.png", "images/UI/inventorySpot.png");
			type.set ("images/UI/inventorySpot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/joinTownButton.png", "images/UI/joinTownButton.png");
			type.set ("images/UI/joinTownButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/languageButton.png", "images/UI/languageButton.png");
			type.set ("images/UI/languageButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/menuButton.png", "images/UI/menuButton.png");
			type.set ("images/UI/menuButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/musicSlider.png", "images/UI/musicSlider.png");
			type.set ("images/UI/musicSlider.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/navigateButton.png", "images/UI/navigateButton.png");
			type.set ("images/UI/navigateButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/nederlandsButton.png", "images/UI/nederlandsButton.png");
			type.set ("images/UI/nederlandsButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/optionsButton.png", "images/UI/optionsButton.png");
			type.set ("images/UI/optionsButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/returnToTownButton.png", "images/UI/returnToTownButton.png");
			type.set ("images/UI/returnToTownButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/selectedSpot.png", "images/UI/selectedSpot.png");
			type.set ("images/UI/selectedSpot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/SFXSlider.png", "images/UI/SFXSlider.png");
			type.set ("images/UI/SFXSlider.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/startButton.png", "images/UI/startButton.png");
			type.set ("images/UI/startButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/test.png", "images/UI/test.png");
			type.set ("images/UI/test.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/title.png", "images/UI/title.png");
			type.set ("images/UI/title.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/tutorialButton.png", "images/UI/tutorialButton.png");
			type.set ("images/UI/tutorialButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/visitBankButton.png", "images/UI/visitBankButton.png");
			type.set ("images/UI/visitBankButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/volumeButton.png", "images/UI/volumeButton.png");
			type.set ("images/UI/volumeButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/watch.png", "images/UI/watch.png");
			type.set ("images/UI/watch.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/UI/zoneActionsButton.png", "images/UI/zoneActionsButton.png");
			type.set ("images/UI/zoneActionsButton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
